    [package]
    name = "SetBonus"
    description = "MWSE Set Bonus Mod and Framework"
    homepage = "https://www.nexusmods.com/morrowind/mods/52911"
    repository = "https://github.com/static/set_bonus"
    authors = ["StaticNation"]
    version = "0.9.8"

    [dependencies]
    assets = [ "Set_Bonus.esp", "MWSE/mods/Static/SetBonus", ]

    [dependencies.mwse]
    buildnumber = 3242

    [tools.mwse]
    lua-mod = "SetBonus"